arrowParens = 'avoid'
bracketSpacing = true
endOfLine = 'lf'
jsxSingleQuote = true
printWidth = 120
quoteProps = 'as-needed'
semi = true
singleQuote = false
tabWidth = 4
trailingComma = 'es5'
useTabs = false
overrides = [
    { files = '*.json', options = { tabWidth = 2 } },
    { files = '*.md', options = { tabWidth = 2 } },
]
